### ISSUE TITLE
Failed to generate animation (Singular matrix error)

### ISSUE THREAD

**Issue by jorvis** [perimosocordiae/route-plotter#1]
Love what you've built here!  I installed it and tried it out with my GPX files from RunKeeper.  It fails when I try to do my last year though.  Attaching the output.

$ ./route_animation.py runkeeper/2016*.gpx --save 2016.mp4 >& 2016.log

[2016.log.gz](https://github.com/perimosocordiae/route-plotter/files/702607/2016.log.gz)

**Comment by jorvis** [comment]
It did just successfully complete my 2015 set though.

**Comment by perimosocordiae** [comment]
Strange, it looks like it's trying to make an image with zero height, which implies that your data doesn't have any variation in latitude. What does it print if you insert this on line 34 of `route_animation.py` (just after the "Filtered to" part)?

    print(_bounding_box(routes))

**Comment by ghost** [comment]
I am seeing this too. I'm using GPX straight out of Strava. I've printed out the bounding box, see below:
```
$:~/route-plotter$ python route_animation.py ../activities/* --save anim.mp4

Parsed 231 valid routes.
Filtered to 123 routes.

BBox(lon_min=-4.1247540000000003, lon_max=-3.4302809999999999, lat_min=52.435833000000002, lat_max=52.758606999999998)

Split into 61377 segments.
Downloading http://c.tile.openstreetmap.org/12/2001/1338.png to /home/andrew/route-plotter/tiles/12_2001_1338.png
[..]
Downloading http://b.tile.openstreetmap.org/12/2008/1344.png to /home/andrew/route-plotter/tiles/12_2008_1344.png
Assembled 0 x 2048 background map image.
Traceback (most recent call last):
  File "route_animation.py", line 255, in <module>
    main()
  File "route_animation.py", line 59, in main
    tail_alpha=args.tail_alpha, head_alpha=args.head_alpha)
  File "route_animation.py", line 109, in _animate
    ax.add_collection(lines)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1459, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/usr/lib/python2.7/dist-packages/matplotlib/collections.py", line 199, in get_datalim
    result = result.inverse_transformed(transData)
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 530, in inverse_transformed
    return self.transformed(transform.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2283, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2283, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 1688, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 520, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

**Comment by perimosocordiae** [comment]
Thanks for the information! Turns out there was an edge case in my background image cropping code, which should now be fixed. Let me know if this hasn't fixed your problem.
