### ISSUE TITLE
How to lower the zoom level

### ISSUE THREAD

**Issue by alesarrett** [perimosocordiae/route-plotter#3]
Running the command
`route_animation.py /mypath/* --save anim.mp4 --max-loop-gap inf`

I have this error:
```
Parsed 22 valid routes.
Filtered to 8 routes.
Split into 3992 segments.
Traceback (most recent call last):
  File "/usr/local/bin/route_animation.py", line 4, in <module>
    __import__('pkg_resources').run_script('route-plotter==0.1.0', 'route_animation.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/route_plotter-0.1.0-py2.7.egg/EGG-INFO/scripts/route_animation.py", line 254, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/route_plotter-0.1.0-py2.7.egg/EGG-INFO/scripts/route_animation.py", line 52, in main
    
  File "build/bdist.linux-x86_64/egg/route_plotter/tile_manager.py", line 53, in stitch_tiles
ValueError: Too many tiles requested (102), try lowering the zoom level
```
where and how can I lower the zoom level?

**Comment by perimosocordiae** [comment]
There a `--zoom` option you can set, like so:

    route_animation.py /mypath/* --save anim.mp4 --max-loop-gap inf --zoom 13

Zoom levels range from 0 to 16, where 0 has one tile covering the whole world and each additional zoom level subdivides the map into two. Depending on how big the area you're trying to plot is, a zoom level between 12 and 15 is usually appropriate.
