### ISSUE TITLE
Setup broken

### ISSUE THREAD

**Issue by ghost** [perimosocordiae/route-plotter#4]
Am I being dim, or is something missing? 

```
$:~/route-plotter$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools

$:~/route-plotter$ ls
LICENSE  README.md  route_animation.py  route_map.py  route_plotter  setup.py
```

**Comment by perimosocordiae** [comment]
Looks like you're using a version of Python that doesn't come with setuptools. These instructions should help: https://packaging.python.org/installing/#install-pip-setuptools-and-wheel

**Comment by ghost** [comment]
Doh, my mistake. I'm a bit of a Python n00b. Sorry!

**Comment by ghost** [comment]
OK, following your suggestion, I install setuptools and tried again. This time things actually happened and I *appear* to now have all the dependencies installed. However, I'm getting an error upon generating a animation. It looks suspiciously like the previous error, however you did indeed fix that earlier, I confirmed that after pulling. This problem only seems to have materialised since I ran the setup. I'm sure this is me being a Python n00b again, apologies!
```
$:~/route-plotter$ python route_animation.py ~/activities/2017/* --color-tiles --save anim5.mp4
Parsed 5 valid routes.
Filtered to 4 routes.
Split into 1996 segments.
Assembled 0 x 2429 background map image.

(route_animation.py:22309): Gtk-CRITICAL **: gtk_window_resize: assertion 'height > 0' failed
Traceback (most recent call last):
  File "route_animation.py", line 254, in <module>
    main()
  File "route_animation.py", line 58, in main
    tail_alpha=args.tail_alpha, head_alpha=args.head_alpha)
  File "route_animation.py", line 108, in _animate
    ax.add_collection(lines)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/axes/_base.py", line 1752, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/collections.py", line 229, in get_datalim
    result = result.inverse_transformed(transData)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 534, in inverse_transformed
    return self.transformed(transform.inverted())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 2401, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 2401, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc2-py2.7-linux-x86_64.egg/matplotlib/transforms.py", line 1797, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 520, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

$:~/route-plotter$ git status
On branch master
Your branch is up-to-date with 'origin/master'
```

**Comment by perimosocordiae** [comment]
Hmm, unless I missed a case this appears to the be the same bug as before. If you do a `git pull`, does it pull down any new changes?

If not, can you try adding the line I suggested in issue #1 and let me know what it prints?

**Comment by ghost** [comment]
OK, I'm definitely up to date:
```
$:~/route-plotter$ git pull
Already up-to-date.
```
and here's the output of `python route_animation.py ~/activities/2017/* --save anim.mp4` (including the additional bounding box print):
```
Parsed 5 valid routes.
Filtered to 4 routes.
BBox(lon_min=-3.939025, lon_max=-3.7495690000000002, lat_min=52.581735000000002, lat_max=52.653677000000002)
Split into 1996 segments.
Assembled 0 x 2429 background map image.
Traceback (most recent call last):
  File "route_animation.py", line 256, in <module>
    main()
  File "route_animation.py", line 60, in main
    tail_alpha=args.tail_alpha, head_alpha=args.head_alpha)
  File "route_animation.py", line 110, in _animate
    ax.add_collection(lines)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1459, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/usr/lib/python2.7/dist-packages/matplotlib/collections.py", line 199, in get_datalim
    result = result.inverse_transformed(transData)
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 530, in inverse_transformed
    return self.transformed(transform.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2283, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2283, in inverted
    return CompositeGenericTransform(self._b.inverted(), self._a.inverted())
  File "/usr/lib/python2.7/dist-packages/matplotlib/transforms.py", line 1688, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 520, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```
Hope it helps!

**Comment by ghost** [comment]
Hi - Is this fixed? I noticed it had been closed, so pulled and tried again, I'm still getting the same error, I'm definitely up to date though:
```
$:~/route-plotter$ git log

commit 44a7054cf8091d1fbe8dc09f7fd9410d197d696b
Merge: 22e983a 761caf9
Author: CJ Carey <perimosocordiae@gmail.com>
Date:   Mon Jan 16 10:22:52 2017 -0600

    Merge pull request #6 from nobbs/master
    
    Fix animation aspect ratio.

commit 22e983aabced0072b0f5a01f275333cb3ea2b622
Author: CJ Carey <perimosocordiae@gmail.com>
Date:   Fri Jan 13 15:26:26 2017 -0500

    Fix issue #1

commit 761caf9174da6760561a5ee086054f0f0101c507
Author: Alexej Disterhoft <disterhoft@uni-mainz.de>
Date:   Fri Jan 13 11:14:34 2017 +0100

    Fix animation aspect ratio.
    
    This also removes the white margin on top and bottom.

....
```

**Comment by perimosocordiae** [comment]
Turns out something as simple as image cropping is kinda tricky to get right for all the edge cases. The latest commit should fix this issue for good, but I'll wait to close until you confirm.

**Comment by ghost** [comment]
That seems to have sorted it! Thanks very much for persevering! Right, time for a good play.

Thanks again!
